name: "Hello World Workflow"

on: 
    push: 
        branches:
            - master
            - test

            
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"

            - name: "print current date"
              run: date

            - name: "who is working on this laptop"
              run: whoami              
