name: "Hello World Workflow - 2"

on: 
    push: 
        branches:
            - master
            - test

    pull_request:
        branches:
            - master
            - test
            - newtest
          
    workflow_dispatch:

            
jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"

            - name: "print current date"
              run: date

            - name: "who is working on this laptop"
              run: whoami   


              
    on-pull:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "check available space"
              run: df -h

            - name: "check current running processess"
              run: ps aux

            - name: "new pull request is asking"
              run: echo "new pull request is done"
        
    on_workflow_dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "new job added"
              run: pwd
  
                       
