name: "Hello World Workflow - 2"

on: 
    push: 
        branches:
            - master
            - test

            
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"

            - name: "print current date"
              run: date

            - name: "who is working on this laptop"
              run: whoami   


              
    checking_system:
        runs-on: ubuntu-latest
        steps:
            - name: "check available space"
              run: du -h

            - name: "check current running processess"
              run: htop
  
                       
